tweets = [
    """Rod Blagojevich, the former Governor of Illinois, was sentenced to 14 years in prison. He has served 7 years. Many people have asked that I study the possibility of commuting his sentence in that it was a very severe one. White House staff is continuing the review of this matter.""",
    """Iran is in serious financial trouble. They want desperately to talk to the U.S., but are given mixed signals from all of those purporting to represent us, including President Macron of France....""",
    """Leaving El Paso for the White House. What GREAT people I met there and in Dayton, Ohio. The Fake News worked overtime trying to disparage me and the two trips, but it just didn't work. The love, respect & enthusiasm were there for all to see. They have been through so much. Sad!""",
    """Just left Dayton, Ohio, where I met with the Victims & families, Law Enforcement, Medical Staff & First Responders. It was a warm & wonderful visit. Tremendous enthusiasm & even Love. Then I saw failed Presidential Candidate (0%) Sherrod Brown & Mayor Whaley totally.....""",
    """Watching Sleepy Joe Biden making a speech. Sooo Boring! The LameStream Media will die in the ratings and clicks with this guy. It will be over for them, not to mention the fact that our Country will do poorly with him. It will be one big crash, but at least China will be happy!""",
    """South Korea has agreed to pay substantially more money to the United States in order to defend itself from North Korea. Over the past many decades, the U.S. has been paid very little by South Korea, but last year, at the request of President Trump, South Korea paid $990,000,000..""",
    """...in 2020. Lou Dobbs stated that this is a fraud on the American public. @peterschweizer stated with certainty that they suppressed negative stories on Hillary Clinton, and boosted negative stories on Donald Trump. All very illegal. We are watching Google very closely!""",
    """Today, I am also directing the Department of Justice to propose legislation ensuring that those who commit hate crimes and mass murders face the DEATH PENALTY - and that this capital punishment be delivered quickly, decisively, and without years of needless delay.""",
    """We cannot let those killed in El Paso, Texas, and Dayton, Ohio, die in vain. Likewise for those so seriously wounded. We can never forget them, and those many who came before them. Republicans and Democrats must come together and get strong background checks, perhaps marrying....""",
    """Our representatives have just returned from China where they had constructive talks having to do with a future Trade Deal. We thought we had a deal with China three months ago, but sadly, China decided to re-negotiate the deal prior to signing. More recently, China agreed to...""",
    """....vindication & exoneration from the Russian, WikiLeaks and every other form of HOAX perpetrated by the DNC, Radical Democrats and others. This is really big stuff especially coming from a highly respected judge who was appointed by President Clinton. The Witch Hunt Ends!""",
    """Wow! A federal Judge in the Southern District of N.Y. completely dismissed a lawsuit brought by the Democratic National Committee against our historic 2016 campaign for President. The Judge said the DNC case was entirely divorced from the facts, yet another total & complete....""",
    """Wow! Morning Joe & Psycho ratings have really crashed. Very small audience. People are tired of hearing Fake News delivered with an anger that is not to be believed. Sad, when the show was sane, they helped get me elected. Thanks! Was on all the time. Lost all of its juice!"""
    ]