months = set([
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
    ])

states = set([
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New", "Hampshire",
    "Jersey",
    "Mexico",
    "York",
    "North", "Carolina",
    "Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode", "Island",
    "South", "Carolina",
    "Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West", "Virginia",
    "Wisconsin",
    "Wyoming",])

trumpisms = set([
    "Sad",
    "United", "States",
    "Clinton",
    "President",
    "Korea",
    "China",
    "LameStream",
    "Media",
])

letters = set([
    "I", "U", "S", "N", "Y", "W", "H",
])

common = set([
    "a","of","to", "that", "and", "the",
])

all = common | letters | trumpisms | states | months
